### ISSUE TITLE
import/export

### ISSUE THREAD

**Issue by fanatid** [calvinmetcalf/buffer-es6#1]
How this package can be used? import/export is not support by any browser/node...
I tried create build with [rollup](https://github.com/rollup/rollup):

x.js:

``` js
import INSPECT_MAX_BYTES from 'buffer-es6'
console.log(INSPECT_MAX_BYTES)
```

```
$rollup x.js -f cjs
Treating 'buffer-es6' as external dependency
'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var INSPECT_MAX_BYTES = _interopDefault(require('buffer-es6'));

console.log(INSPECT_MAX_BYTES)
```

Probably this question about rollup..

**Comment by calvinmetcalf** [comment]
Yes this is for you with my insert node globals and node builtin plugins

**Comment by fanatid** [comment]
Sorry, can you explain in more details?

**Comment by calvinmetcalf** [comment]
I have 2 plugins for rollup one that inserts [node globals](https://github.com/calvinmetcalf/rollup-plugin-node-globals) and one that allows [node builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins) to work with rollup, so if you did

``` js
import {INSPECT_MAX_BYTES } from 'buffer'
console.log(INSPECT_MAX_BYTES)
```

and used the node builtins pluin instead of the common js one or did

``` js
var buf = Buffer.from('I am a buffer');
console.log(buf.toString());
```

with the node globals plugin it would work how you'd expect it to work
